### ISSUE TITLE
popup or not popup

### ISSUE THREAD

**Issue by Monsieur2M** [franck-paul/featuredMedia#1]
Sur Dotclear 2.16.4, lorsque je clique sur "Ajouter un média à la une à cette publication", on me redirige sur une page à l'URL media.php?post_id=14&link_type=featured.

Soit, si j'ajoute un nouveau média et clique sur "Envoyer", la page se recharge (très lentement et péniblement) avec une URL media.php?**popup=0**&select=0&post_id=14&link_type=featured&d=Annonces%2FMAJ

Il n'y a pas quelque chose de bizarre là-dedans ? Au final, cela fonctionne mais il me semble que l'on devrait avoir une popup dès le départ, non ? Un peu comme lorsqu'on insérer un média de la médiathèque dans un billet...

**Comment by franck-paul** [comment]
> Sur Dotclear 2.16.4, lorsque je clique sur "Ajouter un média à la une à cette publication", on me redirige sur une page à l'URL media.php?post_id=14&link_type=featured.
> 
> Soit, si j'ajoute un nouveau média et clique sur "Envoyer", la page se recharge (très lentement et péniblement) avec une URL media.php?**popup=0**&select=0&post_id=14&link_type=featured&d=Annonces%2FMAJ
> 
> Il n'y a pas quelque chose de bizarre là-dedans ? Au final, cela fonctionne mais il me semble que l'on devrait avoir une popup dès le départ, non ? Un peu comme lorsqu'on insérer un média de la médiathèque dans un billet...

Non, le fonctionnement est identique à celui des annexes.
