### ISSUE TITLE
Problème d'encodage dans le titre du média sur la page d'édition de billet

### ISSUE THREAD

**Issue by franck-tomek** [franck-paul/featuredMedia#3]
Si le titre du média contient des caractères diacritiques, dans le contexte d'affichage d'édition de billet dans l'admin, ils s'affichent comme ça �. Problème d'encodage quelque part…

**Comment by franck-paul** [comment]
Ah, alors je manque d'info parce que, testé à l'instant :

![](https://user-images.githubusercontent.com/307049/227761802-ff6b45ab-7d46-43c4-9f1d-26b97c71b85e.jpg)

**Comment by franck-tomek** [comment]
Pourquoi à chaque fois j'ai des bugs bizarres chez moi ? Je vais tester sur plusieurs installs.

**Comment by franck-tomek** [comment]
Bon, le problème semble être uniquement chez Gandi… encore un truc bizarre par chez eux, comme l'histoire des erreurs sur les tables de bdd lors des mises à jour.

**Comment by franck-paul** [comment]
Arf, cela dit faudrait voir quel est l'encodage de la base de données, voire savoir quelle version de MySQL (ou MariaDB) ils utilisent ! 

En attendant on ferme ici

**Comment by franck-tomek** [comment]
Petit rectificatif : j'ai déménagé ce blog sur o2switch mais avec l'héritage de Gandi… ça doit venir de là. On en rediscute sur slack.
