### ISSUE TITLE
Impossible de supprimer un média lié à un billet

### ISSUE THREAD

**Issue by franck-tomek** [franck-paul/featuredMedia#5]
J'ai un média lié à un billet. Je souhaite le supprimer, je clique sur la corbeille, j'ai ensuite une fenêtre JS qui me demande de confirmer, je confirme et là je suis redirigé vers une page qui me dit : "Le plugin que vous essayez d'atteindre n'existe pas ou n'a pas de page d'administration."

DC 2.27.3 / FeaturedMedia 3.0

**Comment by franck-paul** [comment]
C'est retombé en marche ?

**Comment by franck-tomek** [comment]
Je vais retester et te tiens au courant.

**Comment by franck-tomek** [comment]
Non, ça ne fonctionne toujours pas, j'ai le même message d'erreur.
