### ISSUE TITLE
Affichage des images en page d'accueil

### ISSUE THREAD

**Issue by Phi-IP** [franck-paul/featuredMedia#6]
Bonjour,
Je viens d'installer votre plugins avec le theme editorial. Il fonctionne bien et est facile d'utilisation.
Toutefois, les images featured n'apparaissent pas sur la page d'accueil du blog. Les images sont remplacées par l'image par défaut.
Pour autant, les images et les vignettes sont bien présentes dans le répertoire Média.
PS : Dotclear 2.28.1 et Featured 4.1
Cordialement,
Philippe

**Comment by franck-paul** [comment]
Bonjour,

Une URL pour voir ça de visu ? Est-ce que la ou les balises ont bien été mises en place dans le ou les fichiers du thème ? Cache des template vidé ensuite ?

**Comment by Phi-IP** [comment]
Bonjour,
Merci au spécialiste. J'ai vidé le cache des templates et les images sont apparues en homepage.
